### ISSUE TITLE
Analysing data

### ISSUE THREAD

**Issue by m-hume** [solarissmoke/php-dmarc#8]
Hi
Not really an issue, just a request really
Can you provide some sql for analysis of the data? Maybe with some descriptions?
I'm new to analysing dmarc data and could do with a starting point
Cheers
mh

**Comment by joshgeake** [comment]
Yeah I'd really appreciate a report.php script that just displays some useful/meaningful data into a table. I'll have a go myself at some point in the next few weeks and report back. Thanks for all your work!

**Comment by solarissmoke** [comment]
I don't have time at the moment to work on this, but would be more than
happy to merge if you can make a PR with some basic reporting
functionality. Thanks!

**Comment by warlord0** [comment]
I didn't do a report as such, but I added a DNS lookup and placed the data into a model in a Laravel system. So I can scroll it as a table and easily who's failing SPF/DKIM.

But that's all on the work system and it's the holidays! So if you're interested in what it looks like I'll post it in the new year.

**Comment by Tntdruid** [comment]
@warlord0 did you finish it?

**Comment by fesch** [comment]
I've written a fetch script, that fetches the reports and put them into a database thanks to the present project. I would also be interested in any already existing analyzing part. Otherwise I will write it on my own and share it later on (of course ;-))

**Comment by solarissmoke** [comment]
Closing because I don't see myself working on this repo any more - please feel free to fork if you want to develop it further.
